user_options:
  exp: exp0 # 1.5e-04
  debug: True
  shot_number: 8
  seed: 53
  resume: ${resume}
  base: ${config}

data:
  data_root: ${data_root}
  sampled_data_dir: '.'
  train_number: 640
  cand_number: 80
  num_workers: 8

GPT_settings:
  engine: gpt-3.5-turbo #['text-davinci-002', 'gpt-3.5-turbo']
  temperature: 0.0
  max_tokens: 512
  frequency_penalty: 0.1
  presence_penalty: 0.1

reinforce_settings:
  gpu: '0'
  model_config: 'openai/clip-vit-base-patch32'
  lr: 0.001
  epochs: 20
  embedding_size: 128
  batch_size: 20
  policy_temperature: 1.0
  diff_ckpt: 'model.ckpt'
  ckpt_root: ${ckpt_path}
